### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by nyanster**

### CODE REVIEW

**Comment by nyanster** [comment]
This is important because any code people submit to you remains under their full copyright, not yours, unless they sign their intellectual property rights to you. :3

**Comment by BeipDev** [comment]
Good idea, thank you!

**Comment by nyanster** [comment]
omg Benny ;w;
I wasn't expecting this to be accepted, since it makes all the code that's in this github repository (but not any stuff that isn't in this repository) open source.
Thanks <3
t. Theo

**Comment by BeipDev** [comment]
!! I thought that's how it was already, or am I missing something huge here?

**Comment by nyanster** [comment]
Before this license, things were all rights reserved, to you.  This means people aren't legally allowed to do much.  This website explains well:
https://choosealicense.com/no-permission/
Instead, with this license, we now allow people to do pretty much anything they want with stuff in this repository:
https://choosealicense.com/licenses/mit/
(already told BeipDev this, but mentioning it here for the public to read)

**Pull request merged**
